image: node:6.10.0

pages:
  stage: deploy
  script:
  - npm install
  - gulp build
  - mv dist public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master
